### ISSUE TITLE
Loading in DIV

### ISSUE THREAD

**Issue by douglasnoronha** [raphaelfabeni/css-loader#40]
I really enjoyed your project.
I would like to show loading in only one div and not on every page.

**Comment by raphaelfabeni** [comment]
Hey @douglasnoronha ! Sorry about the delay! Really sorry!
It's not possible yet!
For make this possible, there are some CSS changes we need to do.

I think the best way to do it, it would be add a `data-attribute` and in the `CSS`, instead of `position: fixed` we would use `position: absolute`, but then, in your code, you should also add a `position: relative` in the parent element.

What do you think?

**Comment by raphaelfabeni** [comment]
Listed as an improvement. :)
