### ISSUE TITLE
How does this work with npm?

### ISSUE THREAD

**Issue by goldingdamien** [raphaelfabeni/css-loader#46]
I installed with npm but there is no css file in dist.
I tried requiring but that did nothing either.
How do I load the css into the page?

**Comment by raphaelfabeni** [comment]
Hey @goldingdamien ! How are you?
This is tricky because the repository name is `css-loaded` but it's registered as `pure-css-loader`. You can import the CSS files located in `dist/css-loader.css`. But what I want to do it is to add the code for each loader on the demonstration page so you only need to copy it and paste it into your project (something like [this](https://raphaelfabeni.com/ui-interactions/)).
